### ISSUE TITLE
How can this be compared to AWS Lambda?

### ISSUE THREAD

**Issue by geovanisouza92** [force12io/force12#9]

**Comment by lizrice** [comment]
They're quite different approaches to solving a roughly similar problem.  Here are a few of the differences:

* Force12 assumes you've got a (sort-of) fixed cluster of compute power available to you. (By sort-of, I mean that you could perhaps adjust it in a few minutes by scaling VMs, but for real-time purposes the compute is fixed.) 

* Force12 is platform agnostic, whereas AWS Lambda is (obviously) tied to AWS.

* Force12 doesn't care what's in your container, whereas AWS Lambda runs code directly and supports a currently small set of languages: node.js, python and java at time of writing (though I imagine that will grow), and it requires your code to match the [Lambda programming model](http://docs.aws.amazon.com/lambda/latest/dg/programming-model-v2.html).

**Comment by geovanisouza92** [comment]
@lizrice Thank you for explanation.

**Comment by lizrice** [comment]
That's pretty close to my understanding, yes (though I couldn't claim to be a Lambda expert!)  Perhaps another difference is that your docker image could have any number of entry points (it could be one big monolithic application), whereas you have to write a Lambda function for each separate entry point you need to handle. Also Lambda requires your code to be stateless, I believe. 

Thanks for your question by the way!

**Comment by geovanisouza92** [comment]
@lizrice U welcome. Lambda is stateless, what could be anoying thinking about a "12 Factor" function. To simulate an environment variable, I have to use DynamoDB, to avoid putting sensible information inside the function.

Thank you again by the explanations. This project is promising! :)
